Prevent qt from phoning home
rabits/dockerfiles pull request #5
Opened 2021-01-13 10:30 UTC by 131

For version < 5.14, your dockerfiles are not working anymore (as for 2021-01 , if you try the 5.9 android version, you'll see that it remain stuck on the "credential" page with no way to skip)

The installer phone to qt home EVEN with this version that previously did NOT require an account, and now, it does.

But you can prevent this by preventing the QT installer to browse to the net, append --proxy to the qt installer.run and export http_proxy=http://127.0.0.1/ in your dockerfile
The qt offline installer will behave as expected.

2021-01-13 19:57 UTC, rabits commented
Hmmm, interesting... Let me check - maybe there is other way to not allow the installer to be executed with no net connection...

2021-01-15 05:44 UTC, rabits requested changes
Checked the case - it's here, hand right after `[202] Welcome Page`. Also thought about `unshare` - and yep, in docker it's not worked...

But I think it's better to use such env vars directly (like QT_CI_PACKAGES), not as the additional layers.

2021-01-15 05:44 UTC, rabits commented on 5.9-android/Dockerfile
> +ENV http_proxy=http://127.0.0.1/
Maybe better to move right before the command? Like:
```
http_proxy=http://127.0.0.1 /tmp/qt/extract-qt-installer.sh /tmp/qt/installer.run "$QT_PATH"
```

2021-01-17 00:54 UTC, rabits commented
So I just prepared the fix myself) Thank you for the idea, I mentioned you in the commit: https://github.com/rabits/dockerfiles/commit/e5df46f094619d609772d4dea87c154ece4f8411

2021-01-17 00:54 UTC, closed without merging

2021-01-18 14:17 UTC, 131 commented
The --proxy flag in extract-qt was indeed, not mandatory
Thanks for the credit